### ISSUE TITLE
docs: Run mdbook tests on Hydroflow+ docs

### ISSUE THREAD

**Issue by shadaj** [hydro-project/hydroflow#1012]
Not sure how feasible this actually is given that Stageleft is involved, but we need _some_ solution to ensure that the docs aren't out of date. Maybe we should pull the snippets directly from Rust files or something.

**Comment by MingweiSamuel** [comment]
> Maybe we should pull the snippets directly from Rust files or something.

Yeah I set up some stuff for this for the hydroflow quickstart examples

https://github.com/hydro-project/hydroflow/blob/4bdd5568fa0a6674f650f91a029fab302cbf14f4/docs/docs/hydroflow/quickstart/example_5_reachability.mdx#L55-L59

**Comment by MingweiSamuel** [comment]
(half completed in #1318)

**Comment by shadaj** [comment]
Infra set up in #1592, we inline documentation as doctests to ensure they compile.
