### ISSUE TITLE
Semantics for receiving external events

### ISSUE THREAD

**Issue by justinj** [hydro-project/hydroflow#105]
Presently, while we are ticking a stratum, we call `try_recv_events` after each operator, which means that we can receive events at basically any point, meaning a network event which is not present at the beginning of a stratum could show up in the middle of it.

I think there are three obvious behaviours:
1. you can receive an event at any time,
2. you can receive an event in between strata, but not during a stratum,
3. you can only receive events when you loop back around to stratum 0.

I think (2) and (3) might be indistinguishable semantically, but (1) is different. We currently implement (1), I don't have a strong opinion on what the correct behaviour is here, but my understanding was that the desired behaviour was (3). Probably something we should discuss and figure out.

cc @MingweiSamuel @jhellerstein

**Comment by MingweiSamuel** [comment]
Justin's scenario:
Machine A sends out a message in stratum N, machine B responds, machine A receives in same tick and/or later stratum

**Comment by MingweiSamuel** [comment]
#350

**Comment by MingweiSamuel** [comment]
We have implemented (3) you can only receive events when you loop back around to stratum 0.

Related #364

Closed by #377
