### ISSUE TITLE
some persistent ops still replay infinitely on 'static

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#1050]
As surfaced in #800, `fold_keyed<'static...` causes indefinite replay in a cycle. It should behave like `persist` as in #906 and check `if context.is_first_run_this_tick()`. 

Need to check if the same problem arises with `fold` and `reduce` and `reduce_keyed` and `lattice_fold` and `_lattice_fold_batch`.

Fixed?
- [x] `fold` (`lattice_fold`) https://github.com/hydro-project/hydroflow/pull/1134
- [x] `fold_keyed` https://github.com/hydro-project/hydroflow/pull/1086
- [x] `reduce` (`lattice_reduce`) https://github.com/hydro-project/hydroflow/pull/1150
- [ ] `reduce_keyed` #1176

**Comment by MingweiSamuel** [comment]
And `_lattice_join_fused_join` has the problem

**Comment by MingweiSamuel** [comment]
This issue is fixed by inline codegen, which avoids this problem by only ever running the subgraph once. This bug occurs when the subgraph is run twice and (due to errors in implementation) emits items duplicated for each run
