### ISSUE TITLE
Documentation Improvements to the Networking Examples

### ISSUE THREAD

**Issue by rohitkulshreshtha** [hydro-project/hydroflow#1105]
The networking examples rely on the hydro-flow template to explain networking primitives in hydroflow. When the template is updated, the examples become stale. This issue is to make the networking examples bring their own code (like the rest of the examples) so that they do not need maintenance as the template evolves. Template-specific documentation should reside in the template README.md and a separate issue will be created for improvements to that README.

**Comment by MingweiSamuel** [comment]
Can just make the docs reference the template example (so those docs are in one place)
