### ISSUE TITLE
persist should be lattice typed, e.g. to enforce uniqueness of sets

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#1114]
Currently to persist and remove dups you'd have to write:
```
source... -> unique() -> persist()
```
That pays for storing the state twice.

What we'd really like is 
```
source...->persist<SetUnion<T>>()
```
or maybe to support deletion we'd like:
```
source...->persist<MapUnionWithTombstones<HashMap<K, SetUnionHashSet<V>>, HashSet<K>>>
```

**Comment by MingweiSamuel** [comment]
Use `lattice_fold`/`lattice_reduce` with `flatten` after (bit clunky) or, in the future, `state`

**Comment by MingweiSamuel** [comment]
`state` is the new `persist` #1058
