### ISSUE TITLE
Create CONTRIBUTING.md with info for new developers

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#1118]
- #212 - `cargo insta`

**Comment by MingweiSamuel** [comment]
Should include testing info, and info on how update trybuild snapshots, and insta snapshots

cargo install cargo-insta
cargo insta test or cargo test --all-targets --no-fail-fast
cargo insta review

**Comment by rohitkulshreshtha** [comment]
Mingwei, did you want to own this? I won’t be getting to it this week.

**Comment by MingweiSamuel** [comment]
Sure
