### ISSUE TITLE
Running with `--profile profile` crashes with "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by davidchuyaya** [hydro-project/hydroflow#1126]
This outputs "Illegal instruction (core dumped)" on Ubuntu, and "[1]    33846 illegal hardware instruction" on my Mac:
`cargo run --profile profile -p hydroflow_plus_test --example compute_pi`

Help :(

(This runs fine:
`cargo run -p hydroflow_plus_test --example compute_pi`)

**Comment by MingweiSamuel** [comment]
Do you have an ARM mac? Works fine on my old school mac

**Comment by MingweiSamuel** [comment]
Way to fix would be to go to the root cargo.toml and mess with the parameters and see what happens
```toml
[profile.profile]
inherits = "release"
debug = "full"
lto = "off"
strip = "none"
```
