### ISSUE TITLE
Make type of Context.current_tick independent of compilation target instead of `usize`.

### ISSUE THREAD

**Issue by rohitkulshreshtha** [hydro-project/hydroflow#1185]
The type of `Context.current_tick` is `usize`, which is target dependent. On 32 bit platforms, it will be 4 bytes and 64 bit platforms, it will be 8 bytes. In addition to ordering events locally within a transducer, the clock may also be used in cross-transducer clocks (such as vector) clocks. Having a target-dependent size makes it awkward to use because it requires casting.

Using something like `u64` would be cross-platform and big enough for a `long` time.

**Comment by rohitkulshreshtha** [comment]
Instead of just `u64`, I think this should be a newtype. It's a fairly common mistake to mix up clock types in code and primitive types don't save you from that mistake.

**Comment by jhellerstein** [comment]
SGTM

**Comment by shadaj** [comment]
Another thought related to this and exposing the starting `Instant`, should these just be treated as singletons instead? Especially the tick instant could just be a singleton with the RHS constructing a new instant.

**Comment by jhellerstein** [comment]
More generally, we could require the `Context` object be referenced as a
singleton -- in which case user closures get no access to Hydroflow runtime
Rust, only to "system singletons" like `#context`.

**Comment by rohitkulshreshtha** [comment]
It seems reasonable, but I prefer singleton-ification to in a separate issue or PR. This issue/PR should introduce the suitable types.

As to the point about wall-clock timestamps being handled by singleton + RHS constructing new instant. This is a question about ergonomics, and we can collectively pick a direction that makes sense. Certainly, adding every conceivable clock type to the context doesn't make much sense. What is the lowest common denominator of clock types that should be in Context for ergonomics? Does wall clock time belong in that set?

My $0.02 is that it does.

**Comment by shadaj** [comment]
Ooh interesting take, my gut feeling was that wall clock time shouldn't be provided by the runtime through context or any other mechanisms. I will say that I am very biased by the iterates proposal, where `context` effectively cannot exist. In that world, the `iterate` construct provides a local tick count and singletons are how you'd grab a wall clock.

```rust
iterate #i { // #i gives you the current tick ID (a newtype)
    #tick_start = tokio::time::Instant::now();
    ...

    iterate #j { // #j gives you a separate tick counter
        #tick_j_start = tokio::time::Instant::now();
    }
}
```

**Comment by rohitkulshreshtha** [comment]
Looks exceedingly procedural and I mean that in a good way. Is there any additional discussion/documentation of this idea?

**Comment by shadaj** [comment]
Yes! https://www.notion.so/hydro-project/Rethinking-Ticks-Shadaj-efafba357cdb465186275694ce3331df?pvs=4

**Comment by rohitkulshreshtha** [comment]
Also, to be clear, this particular GitHub issue is for the hydroflow scheduler/executor ticks. I'm assuming the design discussion and comments are for clocks other than HF ticks (wall clock/whatever). We can continue the discussion here, just want to get on the same page.

**Comment by rohitkulshreshtha** [comment]
Ok, just saw your link.

**Comment by shadaj** [comment]
Yes correct, I guess there should be a meta-issue on if `context` should exist and if it does what it should provide (hydroflow ticks? wall clock? other metadata?).

**Comment by rohitkulshreshtha** [comment]
Yup. That also seems like a design question and the right forum to discuss that IMHO when reviewing your design proposal. That way the the comments/discussion are easy to discover later. Have you already discussed this with Joe/Mingwei?

**Comment by rohitkulshreshtha** [comment]
https://github.com/hydro-project/hydroflow/pull/1193
