### ISSUE TITLE
Eliminate instants streamed by `source_interval` in the output.

### ISSUE THREAD

**Issue by rohitkulshreshtha** [hydro-project/hydroflow#1186]
`source_interval` emits instances of `tokio::time::instant`. Clocks in the Context (like `current_tick_start`) also indicate the time the tick started. There's some potential for users to confuse these timestamps or fall into the trap of reasoning about the semantics of these clocks/comparability, etc. 

`source_interval` should just emit unit instances `()` when it has data. If someone still needs a clock reading, they can `map` it to something that makes sense for their application.

**Comment by MingweiSamuel** [comment]
Probably should just remove source interval, it's just sugar for:
```rust
source_stream(tokio_stream::wrappers::IntervalStream::new(tokio::time::interval(#arg))
```

**Comment by MingweiSamuel** [comment]
Or can let it return `()`

**Comment by rohitkulshreshtha** [comment]
Fixed.

**Comment by jhellerstein** [comment]
I prefer to keep it, as it shields Hydroflow users from needing to interact
with tokio for this purpose. I concur with the idea that it should return
`()`

**Comment by rohitkulshreshtha** [comment]
Yup, it streams `()` now. Code has been checked in.
