### ISSUE TITLE
Generalized Hash Trie

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#1249]
A data structure used in optimal joins, as described in the [Wang/Willsey/Suciu paper on Freejoin](https://arxiv.org/abs/2301.10841)

**Comment by jhellerstein** [comment]
- [x] basic structure: Insert/Prefix Search/`get()`/`iter()`/`recursive_iter()`
- [ ] lattice integration: `Len`, `Extend`, `Merge` traits
- [ ] testing in `state`/lattice bimorphism
- [ ] testing via hand-written Generic Join on the triangle query from the paper

**Comment by rohitkulshreshtha** [comment]
https://github.com/hydro-project/hydroflow/pull/1308
