### ISSUE TITLE
Type annotation necessary when using output of a cycle in HF+

### ISSUE THREAD

**Issue by davidchuyaya** [hydro-project/hydroflow#1331]
When these two lines do not contain type annotations, the program cannot compile:
[Line 1](https://github.com/davidchuyaya/hydroflow/blob/57df090fe840f4fc998237b17b3dd96e6a15c802/hydroflow_plus_test/src/paxos.rs#L107), [Line 2](https://github.com/davidchuyaya/hydroflow/blob/57df090fe840f4fc998237b17b3dd96e6a15c802/hydroflow_plus_test/src/paxos.rs#L110).

**Comment by davidchuyaya** [comment]
Apparently related to #980 and #1149

**Comment by shadaj** [comment]
Fixed with typed-splicing.
