### ISSUE TITLE
Build broken by type alias enforcing outlives relations

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#139]
https://github.com/rust-lang/rust/pull/95519

**Comment by MingweiSamuel** [comment]
https://github.com/rust-lang/rust/issues/95922

**Comment by MingweiSamuel** [comment]
```rust
#![feature(generic_associated_types)]
#![feature(type_alias_impl_trait)]

trait Gats {
    type Build<'a, 'b>: Fn() -> String;
    fn build<'a, 'b>(a: &'a str, b: &'b str) -> Self::Build<'a, 'b>;
}

type AlphaBuild<'a, 'b> = impl Fn() -> String;

struct Alpha;
impl Gats for Alpha {
    type Build<'a, 'b> = AlphaBuild<'a, 'b>;
    fn build<'a, 'b>(a: &'a str, b: &'b str) -> Self::Build<'a, 'b> {
        || format!("{}{}", a, b)
    }
}
```
[*Playground Link*](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a9c29d34c0fa70bae98b1c75ac33196e)

**Comment by MingweiSamuel** [comment]
doesn't quite reproduce
```rust
#![feature(generic_associated_types)]
#![feature(type_alias_impl_trait)]

use std::fmt::Display;

trait GatsBase {
    type Build<'a, 'b>: Fn() -> String;
}
trait Gats: GatsBase {
    fn build<'a, 'b>(&'a self, b: &'b str) -> Self::Build<'a, 'b>;
}

type AlphaBuild<'a, 'b, T> = impl 'a + 'b + Fn() -> String;

struct Alpha<T: Display>(T);

impl<T: Display> GatsBase for Alpha<T> {
    type Build<'a, 'b> = AlphaBuild<'a, 'b, T>;
}
impl<T: Display> Gats for Alpha<T> {
    fn build<'a, 'b>(&'a self, b: &'b str) -> Self::Build<'a, 'b> {
        || format!("{}{}", self.0, b)
    }
}
```

**Comment by aliemjay** [comment]
I know nothing about hydroflow but noticed that adding `move` to the closure makes it pass.

Was it accpeted previously? That would be surprising!

**Comment by MingweiSamuel** [comment]
[updated playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=71df95d5c5866d3711e3c1881649fbbd)

Thanks! Yeah, that does fix this example, so I guess this wasn't a reproduction of the issue we're having in hf itself. Still working on it.

**Comment by aliemjay** [comment]
reproduced on [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=01fc741f8284f8faf4f3c69dab95c10d)

Fixed by adding `where T: 'a` to the GAT and to the type alias. [playgound](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2bf2081a477955f8850381451038a4ca)

**Comment by MingweiSamuel** [comment]
Oh I didn't know the `where Self: 'a` clause let you bound other type parameters as `'a`, I think that will work!

**Comment by MingweiSamuel** [comment]
Although I guess writing `where Self: 'a` (instead of `where T: 'a` also works? Since `T` is a parameter of `Self`, I guess.
