### ISSUE TITLE
Source subgraph that doesnt call waker won't necessarily be scheduled (bug)

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#143]
Right now there is not anything that reschedules generic source subgraphs. Also check how the context allows scheduling.

**Comment by MingweiSamuel** [comment]
This would apply to `repeat_iter()` in the surface syntax

**Comment by jhellerstein** [comment]
Need a way to repro

**Comment by MingweiSamuel** [comment]
#105

**Comment by MingweiSamuel** [comment]
Creating some issues for `group_by::<'static:>` as well

**Comment by MingweiSamuel** [comment]
Fixed #377
