### ISSUE TITLE
Race condition in TCP & WebSockets Stack

### ISSUE THREAD

**Issue by rohitkulshreshtha** [hydro-project/hydroflow#1458]
The [bind_tcp](https://github.com/hydro-project/hydroflow/blob/afe78c343658472513b34d28658634b253148aee/hydroflow/src/util/tcp.rs#L96) method has a race condition. The client is removed from the hashmap and and back to it across an `await()` boundary. This leaves the client map inconsistent when execution awaits at the await point (the client exists but cannot be found in the map).

Since the newly introduced WebSockets examples rely on the same patterns as TCP, they also have the same race condition.

**Comment by MingweiSamuel** [comment]
#1446
