### ISSUE TITLE
Specialization for handoffs preceeding non-monotone/blocking operators (perf optimization)

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#166]
For example, if we have max() or min(), a preceding handoff would only ever need to store a single max or min element, streaming. But currently we only have VecHandoffs, which store everything. So we can be more efficient. This will probably tie in to using lattice types in handoffs.

**Comment by jhellerstein** [comment]
Another example: Sort is preceded by Handoff, but we could have a HeapHandoff or something that would do most of Sort, and save rebuffering.

**Comment by MingweiSamuel** [comment]
@zzlk is optimizing the current vec handoff

**Comment by jhellerstein** [comment]
Required:
- StatelessHandoff doesn't own state, it participates in the state of its surrounding components

Future Optimization Rule:
- Rewrite rules to identify when we can replace Handoff with StatelessHandoff

**Comment by MingweiSamuel** [comment]
moved to #1500
