### ISSUE TITLE
Emit diagnostics when parsing datalog fails

### ISSUE THREAD

**Issue by shadaj** [hydro-project/hydroflow#181]

**Comment by shadaj** [comment]
tagging @amrita-rajan

**Comment by MingweiSamuel** [comment]
Seems like you can't emit diagnostics on specific spans when everything is spanned as a single string literal? @shadaj

**Comment by shadaj** [comment]
In principle https://docs.rs/proc-macro2/1.0.4/proc_macro2/struct.Literal.html#method.subspan exists on nightly? And we don't really need `syn` since the input is always just a string literal.

**Comment by shadaj** [comment]
Fixed by #467
