### ISSUE TITLE
2pc surface syntax hangs on 10th input

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#218]
not sure why, seems to be something around reading lines from terminal??

**Comment by jhellerstein** [comment]
seems to fail on the 9th input!!

**Comment by MingweiSamuel** [comment]
#281

**Comment by MingweiSamuel** [comment]
Bug fixed by using different implementation in 75f152ef9170982336da0a19dd334b8065975036
But still exists presumably

**Comment by MingweiSamuel** [comment]
Can no longer reproduce in the current version. Tried checking out the old 2PC code (before https://github.com/hydro-project/hydroflow/commit/75f152ef9170982336da0a19dd334b8065975036), does not occur in current runtime
