### ISSUE TITLE
mermaid/dot/json graph generation has two code paths and poor documentation

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#219]

**Comment by MingweiSamuel** [comment]
Regression in 01ff0c6442bf146d4a7e076e2c121ea4c4317ed9

**Comment by jhellerstein** [comment]
Either we should unify the methods for graph generation or at least:

1. Make the surface _syntax_ methos for generating graphs more convenient and natural
2. Rename the surface _API_  something less likely to be misused out of context
