### ISSUE TITLE
modular import of hydroflow graphs

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#220]
It would be good to allow individual hydroflow graph objects to be combined into a bigger graph. Ideally we should be able to take a subgraph S and instantiate it multiple times with different names.

This likely require syntax for explicit "inputs" and "outputs" for these graphs.

[Here's](https://github.com/bloom-lang/bud/blob/master/docs/modules.md) how it was done in Bloom.

**Comment by jhellerstein** [comment]
V1 is local-only Hydroflow
then we'll look at Rust boilerplate for networking

**Comment by zzlk** [comment]
fixed by: https://github.com/hydro-project/hydroflow/pull/898
