### ISSUE TITLE
tolerate badly-formatted messages

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#240]
It's very easy to make hydroflow code panic by sending messages of the wrong type. We should save programmers from needing to handle this defensively.

**Comment by MingweiSamuel** [comment]
Just need to look inside [`source_stream_serde`](https://hydro-project.github.io/hydroflow/book/surface_ops.gen.html#source_stream_serde) and check how it handle's the serde Results, and then either let the user look at those results for `demux`ing or do it directly in this op

**Comment by zzlk** [comment]
#538
