### ISSUE TITLE
Structure-Assuming Ops are a bit frustrating

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#263]
Certain ops assume specifically-structured inputs: notable `join`, `groupby` and `unzip`. This is a common source of tedium and bugs in writing hydroflow. Can we do better? Should we worry about that at this level of the stack?

**Comment by MingweiSamuel** [comment]
Yes at the very least (1) provide some structured way to generate documentation for these cases, and probably also (2) emit some type guards for them in the code

**Comment by MingweiSamuel** [comment]
`sink_serde` and the networked ingress/egresses have address'd pairs

**Comment by MingweiSamuel** [comment]
Seems like carefully designed type guards work very well, sticking with just that #297
