### ISSUE TITLE
Surface syntax can't handle port without arrow: `b = [0]a` or `a[0]`

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#266]
This hydroflow statement:
`msgs = inbound_chan[msgs];`

leads to this error:
`error: expected '->'`

**Comment by MingweiSamuel** [comment]
Notes to self:
So right now variable names only track an input and output operatorId. Would need a different system for referring to specific ports
https://github.com/hydro-project/hydroflow/blob/main/hydroflow_lang/src/graph/flat_graph.rs#L445-L446

**Comment by MingweiSamuel** [comment]
Related: #158
