### ISSUE TITLE
Persistence syntax for surface syntax ("epoch", "static")

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#272]
Supersedes #103 

- [x] join #281
- [x] group_by #281
- [x] cross_join #334
- [x] sort #337
- [x] unique #338
- [x] fold #368
- [x] reduce #368

Related: #166

**Comment by MingweiSamuel** [comment]
Operators which can have epoch vs static persistence:
* `join`/`cross_join`
* `unique`

Operators which would block "forever" with persistence:
* `fold`/`reduce`/`groupby`
* `sort`

**Comment by jhellerstein** [comment]
Why make this distinction? Not clear to me.

**Comment by jhellerstein** [comment]
We can separate the storage semantics (what data is to be sorted) from the output semantics (we do we return a sorted result). The question is whether we should have an opinion on this or leave it controllable.

**Comment by MingweiSamuel** [comment]
Finished in #368
