### ISSUE TITLE
Modify build/docs to promote usage as a library

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#275]
The docs and all our development effort to date is _within_ the `hydroflow` repo. In standard practice, we want hydroflow and its various components to be a library that people `use`. We should make the standard build process produce such a library, and modify the docs to assume library usage (see for example `setup.md`).

**Comment by MingweiSamuel** [comment]
Example library usage: https://github.com/hydro-project/hydroflow-kvs-example/pull/1

**Comment by jhellerstein** [comment]
also https://github.com/hydro-project/hydroflow-template
