### ISSUE TITLE
`recv_iter` is a confusing name 

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#276]
it doesn't really receive anything. 

We should probably think about our source and sink operators and name them all in some coherent, memorable way.

E.g.:
- `recv_iter` => `iter_source`
- `recv_stream` => `stream_source`
- `write_async` => `write_dest`
- `sink_async` => `sink_dest`

The Tokio names are sort of ugly. I'm trying to keep them exposed here but maybe we should give up on them?

**Comment by MingweiSamuel** [comment]
#284
