### ISSUE TITLE
Make a clean, minimalist skeleton for hydroflow apps

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#280]
Currently, even a simple app like an echo server or chat requires a bunch of Rust boilerplate. It would be nice to make most of the boilerplate come from an opinionated library for beginners. This could include:
- serde
- single input/output channels for merge and demux
- perhaps some standard message structs like `SimpleMessage {payload: String, sender: SocketAddr}`
- stdin reader

**Comment by MingweiSamuel** [comment]
It might make sense for some sort of server-client architecture, to cover things like echo server, chat, 2pc. But will always be limiting
