### ISSUE TITLE
associate graph nodes with users's hydroflow variables, plot appropriately

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#327]
It would be helpful for the mermaid/dot graphs to show the users' hydroflow variable names.  Perhaps as (nested?) subgraphs.

To do this we have to propagate the hydroflow variable names into `FlatGraph`, `PartitionedGraph` and `SerdeGraph`.

**Comment by MingweiSamuel** [comment]
Each variable name is associated with a chain of operators. Can implement by adding another secondary map to represent that one-to-many association

**Comment by MingweiSamuel** [comment]
Might be trick to represent as mermaid subgraphs since a variable name might get split across multiple hydroflow subgraphs

**Comment by jhellerstein** [comment]
Can worry about visual representation later; at worst we can print the
variable name in the text on each related operator.
