### ISSUE TITLE
support Hydroflow-only spec files

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#339]
Shadaj's web interface allows Hydroflow to be parsed without any surrounding Rust. We should support that from a CLI, and/or as a project template. We should also consider how that integrates into examples/tutorials/book material.

**Comment by MingweiSamuel** [comment]
Would this just act as a CLI compiler, i.e. spit out generated rust code and/or mermaid graphs?

**Comment by MingweiSamuel** [comment]
And yeah, we probably ought to automate the graph generation at mdbook generation time, which would be pretty feasible I think

**Comment by shadaj** [comment]
discussed this with @jhellerstein yesterday, will spend some cycles exploring how we can combine standalone HF files with Hydroplane to have a unified build+deploy CLI

**Comment by zzlk** [comment]
fixed by: https://github.com/hydro-project/hydroflow/pull/898
