### ISSUE TITLE
VSCode plugin for Hydroflow/Mermaid

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#340]
Would be cool to support @shadaj 's live mermaid generation inside VSCode. Possibly follow the approach used here? https://www.osohq.com/post/building-vs-code-extension-with-rust-wasm-typescript.  

Would this also be a good way to improve intellisense for Hydroflow??

**Comment by MingweiSamuel** [comment]
Marking this low priority for now :P

**Comment by MingweiSamuel** [comment]
#273
