### ISSUE TITLE
document how to output from a `Hydroflow` back to rust

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#342]
- In book: give an example of a `Hydroflow` as a kind of async function
- In docs: fix `hydroflow_lang/src/graph/ops/dest_sink.rs` comment example to be more canonical

**Comment by jhellerstein** [comment]
Need a "sync" sink trait -- basically a pusherator?

**Comment by zzlk** [comment]
My feeling is that we should get rid of `dest_sink`, and only accept sync destinations for now. Until we have a way to implement backpressure then we can't really have the current `dest_sink`

**Comment by MingweiSamuel** [comment]
Cleanup `for_each` in examples/docs and replace with new thing for unbounded channel outputs
