### ISSUE TITLE
Optimizer should minimize use of `'static`

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#347]
As an optimization pass, it would be nice to convert `'static` to `'tick` when possible. For example, consider 

```
my_join = join::<'static, 'static>();
group_by::<'static> -> [0]my_join
... -> [1]my_join
```

We could rewrite the program to be `join::<'tick, 'static>` and the semantics would be the same because the `group_by` will re-feed the `join`. Upstream storage leads to downstream "replenishing". 

As a second level of detail, I suspect there may be optimization *choices* of where in a pipeline we choose to persist -- especially if we can introduce `materialize::<'static>` operators in a plan.

**Comment by MingweiSamuel** [comment]
```mermaid
flowchart TD
    persist["<tt>persist()/deltae()</tt> naïve impl"]
    opdata["parser refactor: op inst. metadata #402"]
    optimize["auto-optimize (rewrite) <tt>persist()/deltae()</tt> #347"]
    joe["joe graphwalking prop algo."]
    rewrite_api["figure out a flexible API for rewriting h.flow graphs"]
    joinstate["split up <tt>join()</tt> state into <tt>persist()</tt>, etc."]
    joinlattice["lattice types in <tt>join()</tt>"]
    joinopt["auto-optimize <tt>join()</tt> state"]

    opdata --> rewrite_api
    joe --> rewrite_api --> optimize
    persist --> optimize --> joinopt
    persist --> joinstate --> joinlattice --> joinopt

    %% david["David dedalus optimizations?"]
    %% rewrite_api --> david
    %% optimize --> david
```

**Comment by zzlk** [comment]
I think this is outdated now that persist() exists (which is what materialize::<'static> is I think?).

**Comment by MingweiSamuel** [comment]
Kinda need state externalization #929 before/for this

**Comment by MingweiSamuel** [comment]
If state externalization worked well we wouldn't even need `'static` vs `'tick`

**Comment by MingweiSamuel** [comment]
Subsumed by #1058 #1050
