### ISSUE TITLE
Efficient Tombstoned lattice

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#366]
In lieu of deletion, we'd like a monotone `'static` op like `fold` or `group_by` that handles tombstones very efficiently -- competitive with deleting from a hash table.

**Comment by jhellerstein** [comment]
See #365

**Comment by MingweiSamuel** [comment]
Some sort of optional negative port to avoid persisting things?

**Comment by zzlk** [comment]
We have decided that what we want to do here is create some optimized tombstoned collection-type lattices which are more effcient than the naive approach.

**Comment by MingweiSamuel** [comment]
Set version is merged #1029

Map union is not merged #1037

**Comment by MingweiSamuel** [comment]
#1038 -> #1052
