### ISSUE TITLE
Add support for `.static` inputs to Dedalus/Datalog programs that emit all values every tick

### ISSUE THREAD

**Issue by shadaj** [hydro-project/hydroflow#375]
Useful for modeling a set of node IDs that messages can be sent to.

**Comment by davidchuyaya** [comment]
Best if this can be populated via a config file, not only for node IDs but also experimental values like leader timeout, quorum size, etc

**Comment by davidchuyaya** [comment]
Requests (can discuss):
Syntax is: `.static nameOfRelation[(v1Attr1, v1Attr2, ...), (v2Attr1, v2Attr2, ...), ...]
For example: `.static replicaAddr[("127.0.0.2", "127.0.0.3")]`.

Stored within `static.dl` in the same directory as remaining Dedalus files. Integrate with hydropilot(?) to dynamically add support for relations such as `local`, which stores the address (or unique ID) of the local machine. Not sure how hydropilot currently plans to link message channels.

**Comment by MingweiSamuel** [comment]
Implemented in #618
