### ISSUE TITLE
Cleaner hydroflow syntax for transducer->transducer networking

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#391]
What does it look like to send data to another transducer? How can it be done in an ergonomic way? Currently it's done relatively externally and then fed into channels which feed into a hydroflow program. This is especially clunky with things like TCP, which tends to be relatively necessary to guarantee order+no packet loss.

This issue is mainly concerned with the user ergonomics, rather than the underlying implementation which should be relatively invisible to the user.

**Comment by jhellerstein** [comment]
- "Named port" operators
- Pull that out of HydroCLI-integration and into Hydroflow
    - Make it possible to do rust-only examples with named ports
    - Keep Hydro CLI externally available for scripting topologies
- Ensure it works with various networking backends including in-proc shmem

**Comment by zzlk** [comment]
Currently I think this goal is under-specified, so it is hard to make progress on it.

**Comment by MingweiSamuel** [comment]
Moved up to hydroflow+
