### ISSUE TITLE
Review use of tokio RwLock throughout CLI

### ISSUE THREAD

**Issue by shadaj** [hydro-project/hydroflow#430]
Also I guess worth double checking all these tokio RwLocks with https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use

_Originally posted by @MingweiSamuel in https://github.com/hydro-project/hydroflow/pull/417#discussion_r1122312910_

**Comment by MingweiSamuel** [comment]
I have gone thru and made all the simple refactors for this, replacing `async RwLock` with `sync Mutex` where possible

#1346 #1347 #1348
