### ISSUE TITLE
Current Difficulties with Surface API

### ISSUE THREAD

**Issue by justinj** [hydro-project/hydroflow#59]
A list of some stuff we discussed today while working through exchange.

## Extend is tricky

Having to do fancy type-level list concatenation to write an operator is Not So Much Fun. It definitely gives us a lot of power and safety, but I think the amount that the average user will be exposed to it today is a bit unfortunate, especially because they don't conceptually feel (to me, at least) like an essential part of the type I'm describing when I write a function.

## Lifetimes are difficult when implementing the Build structs.

This might just be my inexperience with explicit lifetimes, but there's quite a lot of machinery to go through to get something working. This one I could see getting resolved once we have sufficiently many examples, though.

## Stream Completion

This should be its own issue for discussion, perhaps.

Can we easily thread metadata through a pipeline here?

We sort of want something like the tokio streams, kind of looking like this:
```rust
enum Msg<T> {
    PartialStop,
    TotalStop,
    Data(T)
}
```
but as it is, the iterators expect `Option`s, and its not clear how to pass these through the tree. Another option would be to have a parallel tree that manages the metadata, but that seems kind of hard and difficult to make safe.

@jhellerstein @MingweiSamuel

**Comment by jhellerstein** [comment]
Surface API is deprecated
