### ISSUE TITLE
When a send to a `dest_sink` fails, we should avoid printing out the entire payload

### ISSUE THREAD

**Issue by shadaj** [hydro-project/hydroflow#595]
<img width="758" alt="Screenshot 2023-04-15 at 10 23 44 PM" src="https://user-images.githubusercontent.com/543055/232272733-94a0985b-d4a5-4bd2-b96e-574a58bb03ae.png">

**Comment by zzlk** [comment]
Wow this was surprisingly hard to track down, I had to actually repro it locally to find out exactly where it was coming from. It's actually coming from the mpsc::send, when that fails it returns a SendError(payload), which gets dumped to debug output from expect().

https://docs.rs/tokio/latest/tokio/sync/mpsc/error/struct.SendError.html

minimal repro:
```rust
    let (tx, rx) = tokio::sync::mpsc::unbounded_channel::<String>();
    std::mem::drop(rx);
    tx.send("payload".to_owned()).expect("destroy my terminal");
```
produces
```
thread 'main' panicked at 'destroy my terminal: SendError("payload")', hydroflow/examples/hello_world/main.rs:8:35
```

Notably, the Display impl for SendErr does -not- dump the failed-to-send object to the terminal:

```rust
    let (tx, rx) = tokio::sync::mpsc::unbounded_channel::<String>();
    std::mem::drop(rx);
    println!(
        "destroy my terminal: {}",
        tx.send("payload".to_owned()).unwrap_err()
    );
```

```
destroy my terminal: channel closed
```

I will send a PR.
