### ISSUE TITLE
Occasional segfaults in CI hydro_cli python tests

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#619]
`rustup run "$(grep -oP '(?<=channel = ")\S+(?=")' ../../rust-toolchain.toml)-x86_64-unknown-linux-gnu" pytest *.py`

https://github.com/hydro-project/hydroflow/actions/runs/4793445751/jobs/8525897151

https://github.com/MingweiSamuel/hydroflow/actions/runs/4801308808/jobs/8543354009
`/home/runner/work/_temp/9c22d61f-32ed-4304-a571-be2d8780ab85.sh: line 5: 15477 Segmentation fault      (core dumped) rustup run "$(grep -oP '(?<=channel = ")\S+(?=")' ../../rust-toolchain.toml)-x86_64-unknown-linux-gnu" pytest *.py`

**Comment by shadaj** [comment]
Very interesting, this is happening _after_ the tests finish so something wrong with Python shutdown logic.

**Comment by shadaj** [comment]
These seem to be less "occasional" and more "all the time", investigating...

**Comment by shadaj** [comment]
It seems we are not the only ones facing this: https://github.com/temporalio/sdk-python/issues/300

**Comment by shadaj** [comment]
(finally) fixed by #699
