### ISSUE TITLE
Use tokio-stream to handle multiple incoming TCP connections

### ISSUE THREAD

**Issue by shadaj** [hydro-project/hydroflow#659]
Maybe makes sense to use https://docs.rs/tokio-stream/0.1.14/tokio_stream/wrappers/struct.TcpListenerStream.html which is `Stream<Item = Result<TcpStream>>` wrapper around the `listener`

Instead of the separate task and mpsc unbounded

_Originally posted by @MingweiSamuel in https://github.com/hydro-project/hydroflow/pull/656#discussion_r1195458569_

**Comment by MingweiSamuel** [comment]
https://github.com/hydro-project/hydroflow/blob/d3a5f51ad83e55c111aef3bba743ea88756c4037/hydro_deploy/hydroflow_cli_integration/src/lib.rs#L140-L149
