### ISSUE TITLE
(lattice) operator names, need holistic review of joins/batch/persist/etc to make sure the names are consistent

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#665]
Decisions
* [x] #695
* [x] #700
  * except lattice!
* [x] #703
* let’s keep identity. It has 2 uses: type constraints, and internal use for “empty” components between handoffs (which may go away in future).
* [x] #701
* our sort_by is rust sort_unstable_by_key. This is fast, and we like it.
* [x] #713
  * [x] add spin() and remove repeat_iter_external()
  * [x] replace repeat_iter with source_iter({})->persist()
  * [x] replace repeat_fn with source_iter({}) -> persist() -> map()
* [x] #705
  * Affect on join? (for now implicitly cross_join_keyed)
* [x] #707
  * ‘tick behavior makes this not affect control flow
* [ ] #725
  * must partition input
  * any copying etc can be done with tees/merges
* [ ] #724
  * identity with triggered release (quantity or dataflow) – a la cross-join
  * lattice_batch is a combo of a fold and a triggered release
* [x] #710
* [x] #727

modifiers (*_keyed, *_by_key, lattice_*) go after operator name
* Do we have the cross product of ops and modifiers thought through?
  * e.g. unique_by**_key**
  * e.g. join_by**_key**: no perf benefit bc we extract key to hash 
  * difference_by**_key**: perf benefit on the positive (left) side
  * sort_by**_key**: perf benefits
  * unique_by**_key**: perf benefits (only store keys)
* Are the modifiers disjoint
  * lattice, keyed, by_key are pairwise disjoint

---
old body:

lattice vs non-lattice.
reduce vs batch.
persistence.

What precisely is the difference between lattice_merge(reduce) and lattice_batch, what is the difference between batch and persist?

Reduce vs batch is very different, because reduces from N to 1 tuple, and batch does not reduce, it just batches together N tuples and releases N tuples. Lattice batch seems to do a certain amount of reducing as well because of the implicit merge in it, so it behaves a lot like a reduce followed by a batch. Should it still be called lattice_batch?

**Comment by zzlk** [comment]
rename merge() to something like interlace()?

**Comment by MingweiSamuel** [comment]
Maybe we should just rename `merge()` to `chain()` as the rust-ism and add a \*this has no specific order

Itertools has interleave although that also has ABABAB order implication https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.interleave

**Comment by zzlk** [comment]
hmm, merge is just chain() under the covers. The interleaving/non-ordering comes from new ticks. So, I would vote for it to be called chain() with an asertix about the ordering thing across ticks.
