### ISSUE TITLE
examples like template echoserver do not run in CI/test and provide no coverage

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#698]

**Comment by MingweiSamuel** [comment]
check if hydroflow/examples/kvs_bench/protocol/test/mod.rs tests run

**Comment by jhellerstein** [comment]
And update template/docs as well!

**Comment by zzlk** [comment]
partially fixed by https://github.com/hydro-project/hydroflow/pull/791

**Comment by zzlk** [comment]
other partially fixed by https://github.com/hydro-project/hydroflow-template/pull/9
