### ISSUE TITLE
add zip & zip_longest

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#707]

**Comment by MingweiSamuel** [comment]
Unfortunately I dont think there's a way to implement zip_longest right now in the face of loops .. there's no way to know if (1) the tick is ending or (2) more items will come for lhs or rhs

**Comment by jhellerstein** [comment]
So you're saying that zip_longest is a non-monotone op?  Thats fine right? Needs to be stratified and have sealed inputs. Sent from a telephoneOn May 25, 2023, at 12:42 PM, Mingwei Samuel ***@***.***> wrote:﻿
Unfortunately I dont think there's a way to implement zip_longest right now in the face of loops .. there's no way to know if (1) the tick is ending or (2) more items will come for lhs or rhs

**Comment by MingweiSamuel** [comment]
Yeah that actually would be fine too, treat zip_longest as non-monotone, stratify both of its inputs
