### ISSUE TITLE
figure out spin() semantics

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#720]
Shadaj asked me this question and I believe they're pretty much equivalent, maybe source_interval(0) has slightly more overhead. But source_interval(0) has the advantage of being much clearer I think and removes one operator.

**Comment by jhellerstein** [comment]
Let's leave the syntax but it should codegen `source_interval(Duration::new(0))`

**Comment by zzlk** [comment]
I think we might need to think about this a bit more.

source_interval(Duration::from_secs(0)) is not possible in tokio. It panics immediately. Likely the reason for asserting that duration > 0 is because an interval with period 0 is probably not that useful. It would mean that whenever you poll the interval it would always return Ready(). If we used such a thing in hydroflow it means that hydroflow would try to extract an infinite amount of items from this interval which would cause it to run out of memory.

spin() on the other hand has different behavior. It causes the scheduler to tick but the operator itself only emits one item.

**Comment by jhellerstein** [comment]
SGTM

**Comment by jhellerstein** [comment]
What data does `spin()` output each tick? A Unit()? 
Let's get a uniform answer across `spin()` and `source_interval()`.
#623

**Comment by jhellerstein** [comment]
resolved in #714 via `spin()`
