### ISSUE TITLE
consider organizing operators in docs according to taxonomy below?

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#727]
Binaries: anti_join, cross_join, difference, join, lattice_join, merge

Maps: enumerate, filter, filter_map, for_each, identity, inspect, map: all borrowed directly from Rust

Flattens: flat_map, flatten: all borrowed directly from Rust

Standard Folds: fold, reduce: borrowed directly from Rust

Keyed Folds: group_by, keyed_fold, keyed_reduce

Lattice Folds: lattice_batch, lattice_merge (should use reduce)

Persistences: batch, lattice_batch, persist, sort, sort_by, unique

Tees: demux, tee, unzip

Generators: initialize, null, spin, source_*

Repeat Generators: repeat_fn, repeat_iter, repeat_iter_external, 

Sinks: dest_*, null

Control Plane: next_stratum, next_tick, repeat_iter_external

**Comment by MingweiSamuel** [comment]
| All Operators | | | |
| --- | --- | --- | --- |
| [`anti_join`](#anti_join) | [`batch`](#batch) | [`cross_join`](#cross_join) | [`demux`](#demux) |
| [`dest_file`](#dest_file) | [`dest_sink`](#dest_sink) | [`dest_sink_serde`](#dest_sink_serde) | [`difference`](#difference) |
| [`enumerate`](#enumerate) | [`filter`](#filter) | [`filter_map`](#filter_map) | [`flat_map`](#flat_map) |
| [`flatten`](#flatten) | [`fold`](#fold) | [`fold_keyed`](#fold_keyed) | [`for_each`](#for_each) |
| [`identity`](#identity) | [`initialize`](#initialize) | [`inspect`](#inspect) | [`join`](#join) |
| [`lattice_batch`](#lattice_batch) | [`lattice_join`](#lattice_join) | [`lattice_merge`](#lattice_merge) | [`map`](#map) |
| [`multiset_delta`](#multiset_delta) | [`next_stratum`](#next_stratum) | [`next_tick`](#next_tick) | [`null`](#null) |
| [`persist`](#persist) | [`reduce`](#reduce) | [`reduce_keyed`](#reduce_keyed) | [`sort`](#sort) |
| [`sort_by_key`](#sort_by_key) | [`source_file`](#source_file) | [`source_interval`](#source_interval) | [`source_iter`](#source_iter) |
| [`source_json`](#source_json) | [`source_stdin`](#source_stdin) | [`source_stream`](#source_stream) | [`source_stream_serde`](#source_stream_serde) |
| [`spin`](#spin) | [`tee`](#tee) | [`union`](#union) | [`unique`](#unique) |
| [`unzip`](#unzip) | [`zip`](#zip) | [`zip_longest`](#zip_longest) |
