### ISSUE TITLE
mermaid styling in docs makes font colors troublesome

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#737]
The mermaid we emit from hydroflow picks a white font for blue boxes and black font for yellow boxes.

Mermaid in the docusaurus docs adds a white background for `<code>` but not for other text. For boxes with dark background (e.g the blue boxes) the `<code>` blocks become illegible. Even if you edit the mermaid output from Hydroflow manually, it's difficult to pick a font color that contrasts well with both the blue background (non-`<code>`) and the white background (`<code>`).

<img width="323" alt="image" src="https://github.com/hydro-project/hydroflow/assets/384577/e9300e99-17da-4c35-8561-99f9d27ca6d6">

**Comment by shadaj** [comment]
@jhellerstein looking into this now, do you remember which page you found this on? at least in the playground, the code snippets always have black text

**Comment by jhellerstein** [comment]
In the book.
