### ISSUE TITLE
lattice merge should probably use fold()

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#752]
currently lattice_merge uses reduce with Merge as the reducing function. Usually you want to merge in singleton tuples and so the type of the input and the output of the reducing function is different, which implies a fold.

**Comment by MingweiSamuel** [comment]
https://github.com/hydro-project/hydroflow/pull/711 :P

**Comment by zzlk** [comment]
:)

I guess we want it both ways.

If type_of(x.merge(y)) == type_of(y) then we can use reduce and not require that x be wrapped in bot/impl default
if type_of(x.merge(y)) != type_of(y) then we have to use fold and that would require that x be wrapped in bot/impl default

**Comment by jhellerstein** [comment]
Why not `lattice_fold` and `lattice_reduce`? Seems like that is ergonomic to rust and general enough to deal with singletons vs collections, etc.

**Comment by zzlk** [comment]
Decided to go with lattice_fold and lattice_reduce
