### ISSUE TITLE
hide lattice internals?

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#768]
the rust crdt crate really tries to hide the lattice internal state so you can arbitrarily mutate it or read it randomly. It manages all this with this concept of 'contexts' and 'ops'

I think we don't need to do something so heavy weight but maybe we can provide some accessor traits so that users know when they read state from inside the lattice like that it will be non-monotone/comes with some level of warning.

```rust
fn main() {
    let mut vclock = VClock::new();
    vclock.apply(Dot::new(31231, 2));
    vclock.apply(Dot::new(4829, 9));
    vclock.apply(Dot::new(87132, 32));
    println!("vclock:\t{}", vclock);

    let mut reg = MVReg::new();

    let op1 = reg.write("some val", reg.read().derive_add_ctx(9_742_820));
    let op2 = reg.write("some other val", reg.read().derive_add_ctx(648_572));
    reg.apply(op1);
    reg.apply(op2);

    println!("reg:\t{}", reg);
}
```

**Comment by jhellerstein** [comment]
We should not have public members. Getters/Setters should be named something fateful (Peek/Poke?) and should return a non-monotone property flag.

**Comment by jhellerstein** [comment]
Get of a value that is Top is monotone.
