### ISSUE TITLE
`fold/reduce` should take `&mut` instead of by-value input params to match `fold/reduce_keyed`

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#770]
fold_keyed and reduce_keyed both take &mut because implementing them on top of by-value reducing functions is awkward/inefficient. Should fold/reduce be changed to &mut for consistency or be kept as by-value to maximize their flexibility.

I'm not sure what changing to &mut would prevent in fold/reduce, I don't suspect it would have much impact on optimization because the &mut borrow is only held for the duration of the reducing function call, so it is equivalent(?) to moving into and then moving out of the closure.

**Comment by jhellerstein** [comment]
Is it possible to allow both usages? Should we think about the codegen reasoning about argument types?
