### ISSUE TITLE
should join() eventually be replaced with lattice_join()?

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#776]
lattice_join currently requires you to specify lhs/rhs type. We could make lattice_join without lhs/rhs type specifiers default to some ssiv-like type and then remove join(), so all joins would be lattices in hydroflow.

This is related to the long running question of what semantics should join() have, sets or multisets?

**Comment by zzlk** [comment]
join is now multiset join: https://github.com/hydro-project/hydroflow/pull/774

**Comment by jhellerstein** [comment]
Join is no longer multiset join: #804

**Comment by jhellerstein** [comment]
This should follow naturally after https://github.com/hydro-project/hydroflow/issues/271, as we sweep through operators and make them properly typed for lattice-valued edges.
