### ISSUE TITLE
rga --impl datalog-agg example hangs, cycles infinitely (rewrite with new bimorphism join)

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#800]
`cargo run -p hydroflow --example rga -- --impl datalog-agg`

**Comment by jhellerstein** [comment]
possibly due to #963 ?

**Comment by MingweiSamuel** [comment]
(reproduced just now -@jhellerstein)

**Comment by MingweiSamuel** [comment]
nextSibling's fold_keyed is replaying forever in tick 0 stratum 1. may be a bug in the op implementation?

**Comment by MingweiSamuel** [comment]
Caused by #1050

**Comment by MingweiSamuel** [comment]
Change in plans: rewrite via #1073 #1063 to just dodge the #1050 bug

**Comment by MingweiSamuel** [comment]
![image](https://github.com/hydro-project/hydroflow/assets/6778341/88cd38c5-6978-4431-9b31-9a79dbb26752)
