### ISSUE TITLE
generate all example outputs in book from experiment tests

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#814]
Currently, output from examples, as in `docs/docs/hydroflow/quickstart/setup.md`, can get out of sync with the code. We should replace all such.

**Comment by MingweiSamuel** [comment]
From #795 Jun 29, 2023

docs\docs\hydroflow\quickstart\setup.md
docs\docs\hydroflow\quickstart\example_7_echo_server.mdx
docs\docs\hydroflow\quickstart\example_8_chat_server.mdx

docs\docs\hydroflow\syntax\surface_flows.md
