### ISSUE TITLE
Should `lattice_join()` take in `MapUnion<K, Lat>` instead of `(K, Lat)`?

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#819]

**Comment by zzlk** [comment]
I think it should, I have a local branch with some changes in this direction already.

**Comment by jhellerstein** [comment]
This is a fusion op and should be named appropriately, see #832

**Comment by zzlk** [comment]
After discussing this issue a lot, we decided that actually (K, Lat) is the correct input format for lattice_join, and we also decided that lattice_join is a very specialized version of the more generic idea that reduce preceding join should have a dedicated fusion operator for it.

**Comment by jhellerstein** [comment]
handled by #861
