### ISSUE TITLE
Heavy type inference is confusing

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#824]
We have this recurring issue with deep type inference where a constraint is placed upstream and a constraint is placed downstream and these two constraints are incompatible with each other. The type inference happens in a confusing way because of push/pull side of the graph, eventually a conflict is discovered and rust surfaces it in usually a pretty confusing place.

Not sure what to do about this.

**Comment by jhellerstein** [comment]
Hydroflow+ will at least raise this in the IDE, but realistically it's hard to imagine making this problem go away given how Rust type inference works. Most developers will work around via explicit typing.
