### ISSUE TITLE
expand assertion ops

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#825]
`assert` => `assert_eq` 
add `assert{|x| f}` where `f: <type of x> -> bool` 

can add more convenience ops if we want

**Comment by zzlk** [comment]
also need to add something like "prefix_assert" so we can assert things over ticks, an example of that would be

a = prefix_assert([1, 2, 3, 4])

first tick:
[1, 2] -> a = OK

second tick:
[3, 4] -> a = OK

another thing to add would maybe be some kind of reduce-then-assert.

**Comment by jhellerstein** [comment]
Maybe instead of "prefix_assert" call it "assert_zip_eq"?

**Comment by MingweiSamuel** [comment]
Yeah lets keep the `assert_` prefix consistent

**Comment by jhellerstein** [comment]
Need a 'static persistence for multi-tick assertions?
