### ISSUE TITLE
Diagnostics: ops need some ergonomic way of generating flow of debug info (e.g. flag when all work is done)

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#834]
It is very common in imperative code to perform some work and wrap it in wall-clock timers or event logging so that they can accurately keep track of when a request is finished processing. This is difficult in hydroflow to do completely correctly. Usually what will happen is that they will emit some event slightly before the request has been completely processed for example:

```rust
req -> inspect(|x| println!("request finished processing")) -> join<'static>()
```

but this is not completely correct because the event is emitted slightly before all the 'work' has been done.

Another way to do this would be to use run_tick() and emit once run_tick() finishes but this is not very ergonomic and does not cooperate well with async.

**Comment by jhellerstein** [comment]
Many ops don't necessarily produce data for each unit of work. E.g. join may consume without producing.

**Comment by jhellerstein** [comment]
Generally would be nice to have an operator API for DEBUG/LOG stream out of an operator. As regards "work is done", this seems operator-specific.

One possible API:
```
   chain = op1() -> op2();
   chain.debug() -> inspect(...)
```

**Comment by zzlk** [comment]
For 'work is done' I did this change https://github.com/hydro-project/hydroflow/pull/887 and I think that is good for the 'work is done' use case which was the primary driver of the demand for this.

**Comment by jhellerstein** [comment]
Currently we have a recipe for compiling and generating flamegraphs that captures all the operator paths (we think). But it aggregates that across all calls. Perhaps we'll decide that + `inspect` is adequate, but some design requirements would probably be good here. Maybe that can be driven by users like @davidchuyaya.

**Comment by MingweiSamuel** [comment]
[`metrique`](https://crates.io/crates/metrique) provides an interesting take on this, where metrics are stored within an RAII struct instance, which is finalized (pushed to a queue to be emitted) once dropped
