### ISSUE TITLE
document `kvs_bench` example

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#856]
We should provide a useful `README.md` for `kvs_bench`. Ideally we separate the functionality of the KVS from running the benchmark. Then document ~~(a) how to deploy the KVS for normal use,~~ and (b) how to reproduce benchmark results.

It would be nice if this subsumed the KVS example.

**Comment by MingweiSamuel** [comment]
3c8dbd709fa5a1c1a458d2aa5e2be9ecd8fc4b49
