### ISSUE TITLE
Hydroflow Spins

### ISSUE THREAD

**Issue by justinj** [hydro-project/hydroflow#87]
An idling Hydroflow instance makes my (and Mingwei's) fans go crazy and take up 100% cpu. We should fix that.

**Comment by MingweiSamuel** [comment]
I believe this only happens with [`hf.run_async()`](https://hydro-project.github.io/hydroflow/doc/hydroflow/scheduled/graph/struct.Hydroflow.html#method.run_async) and not with `hf.run()`
