### ISSUE TITLE
Add a `is_new_tick` (`is_first_run_in_tick` or `!is_repeat_run`) parameter to #context or somewhere else

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#875]
We have a lot of operators that replay now, and when they replay they need to know whether it is a new tick or not. This logic is currently duplicated in many places throughout the code and could be centralized into a parameter that can be directly checked.

**Comment by MingweiSamuel** [comment]
Yeah we should put this in the context, though that does mean we probably have to track a bit more for when subgraphs run

**Comment by jhellerstein** [comment]
Once done, clean up the redundant parts of the code that check this manually.
