### ISSUE TITLE
an assert_eq_multiset() op would be nice

### ISSUE THREAD

**Issue by zzlk** [hydro-project/hydroflow#876]
Now that we have joins that re-order their input when they replay. assert_eq is a lot less useful since it enforces order. assert_eq_multiset would ignore the order and assert that the same items occur and the number of times they occur is correct.

**Comment by jhellerstein** [comment]
(1) this is not a `set`/`multiset` issue, it's an `ordered`/`unordered`
issue.
(2) it's easy enough to add a `sort()` when debugging, and it works in
either the `set` or `multiset` setting.
