### ISSUE TITLE
Handle error when launching HydroflowCrate in `hydro_deploy`

### ISSUE THREAD

**Issue by tiemobang** [hydro-project/hydroflow#889]
When launching a the executable of HydroflowCrate incurs a error and the executable crashes, Hydrodeploy currently does not catch the error but waits until the timeout of the launch and exits without a notification about the incurred error.

**Comment by MingweiSamuel** [comment]
@shadaj Have you fixed or improved this?

**Comment by MingweiSamuel** [comment]
This is improved and will at least print out the stdout/stderr of the failed command for the user to see
