### ISSUE TITLE
Hydroflow Challenges Floating Around

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#916]
- SSIV and immutables and other things aren't really lattices, the code that generates them can't be replicated. It's kind of like forming a quotient lattice out of a family of possible quotient lattices or something. Let's get this right in the type system.
- Replaying operators with downstream filters shouldn't redundantly generate irrelevant facts (some kind of semi-join trick needed) #616

**Comment by MingweiSamuel** [comment]
First bullet, #1119 maybe
