### ISSUE TITLE
Hydroflow Generality: Benchmarking and Expressivity

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#930]
Performance
- How low is our latency for a simple flow? Identity? Anna? Can we get to "line rate"? How does the KVS bench compare? 
- Can a fast box with many Hydroflow transducers handle a high-speed (40Gb?) NIC?
- Similar questions for bandwidth -- seems easy, but have we done something wrong?
- What else should we benchmark?
- We get lots of goodness from "shared nothing". What's the downside of explicit comm vs shared memory? Let's do some adversarial analysis of our weaknesses.
- Revisit early timely comparison?

Expressivity
- Is `map` and `fold` enough generality for non-dataflow user code?
- If you're justifying that you're "a general language", what constructs do you need to demonstrate?
- What about linear algebra/ML?

**Comment by MingweiSamuel** [comment]
#1074
