### ISSUE TITLE
Stratum barriers are displayed as non-monotonic, need more nuanced analysis

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#943]
diagram of benchmarked KVS has stratum boundaries but still should be analyzable as monotonic

**Comment by MingweiSamuel** [comment]
![image](https://github.com/hydro-project/hydroflow/assets/6778341/627f3040-5c29-45d8-b3b9-24ebd0f7e076)

**Comment by jhellerstein** [comment]
Seems like we could have different edge types:
- streaming
- cumulative per tick (one item per tick)
- cumulative/static (one item when computation is known to be complete)

Note also that operator implementations may reason about this. E.g. single-sided tick-based hash-join needs cumulative per-tick on the "build" side, and a stratum boundary to compute that one item per tick.

**Comment by jhellerstein** [comment]
lattice operators are monotonic and shouldn't be put in a new stratum.

**Comment by MingweiSamuel** [comment]
(Supposed to have been fixed by https://github.com/hydro-project/hydroflow/pull/1026/files#diff-24703f4800f245533293880082a894cd126bb4196c03d16981698df500b064c3 but wasn't)

**Comment by MingweiSamuel** [comment]
Looks like just that `_lattice_join_fused_join`'s `input_delaytype_fn` wasn't updated: https://github.com/hydro-project/hydroflow/pull/1026/files#diff-91beeca3fb8853d5710c860e12c097f15544a8c13cab30cd51daa6d6b32b45a9R91
