### ISSUE TITLE
ICE when fold accumulator type annotation is incorrect

### ISSUE THREAD

**Issue by RyanAlameddine** [hydro-project/hydroflow#951]
The following code snippet causes an internal compiler error on my version of rust (rustc 1.75.0-nightly):
```
source_iter(vec![1]) 
    -> fold(Vec::new, |accum: Vec<usize>, elem| {accum.push(elem)}) 
    -> assert_eq([vec![1]]);
```
Note that the mistake is is that `accum: Vec<usize>` should be `accum: &mut Vec<usize>`.

Also, I'm curious why the type of accum can't be inferred.

**Comment by MingweiSamuel** [comment]
Maybe https://github.com/rust-lang/rust/issues/116658
