### ISSUE TITLE
hash join with keyed storage

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#969]
We should allow hash join to accept any keyed lookup structure as pre-populated storage. E.g. it should be possible to do a hash join over a `persist_mut_keyed` without scanning, or perhaps over any collection object that accepts key lookups.  

Said differently, it should be possible to do key-based lookups in collection objects like `persist_mut_keyed` without scanning.

**Comment by MingweiSamuel** [comment]
#929

**Comment by MingweiSamuel** [comment]
#1058 #1050

**Comment by MingweiSamuel** [comment]
Mechanism is implemented in `lattice_bimorphism` for now via #1061 #1159

Should dogfood it a bit more
