### ISSUE TITLE
infinite sources and zip over time

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#970]
In an unbounded streaming world, it makes sense to me to have unbounded sources like `source_iter_unbounded(0)` that starts at the argument (`0`) and generates an unbounded sequence of increasing values. (Rust doesn't seem to provide this in any built-in way.)

It would also make sense in Hydroflow to have a zip variant `zip_across_ticks` where instead of truncating the longer input, it continues it on the next tick.

With these two constructs there's a very clean implementation of a sequencer for an unbounded stream:
```
source_stream(..) -> [0]sequenced_stream;
source_iter(0..) -> [1]sequenced_stream;
sequenced_stream = zip_across_ticks() -> ...
```

**Comment by jhellerstein** [comment]
Lucky comments that `cross_join::<'tick, 'static>` should probably have an analogy like this one for `zip::<'tick, 'static>`.

The example above is not great, as there are many other ways to do this in both Hydroflow and Rust. But the issue remains.

**Comment by MingweiSamuel** [comment]
```rust
hydroflow::util::iter_batches_stream(0.., 50)
```

**Comment by jhellerstein** [comment]
using `enumerate` should be good enough in most cases.
