### ISSUE TITLE
API stability concern

### ISSUE THREAD

**Issue by discord9** [hydro-project/hydroflow#977]
Hello I'm trying to use hydroflow as a underlying computation layer for a simple aggerate system, I wonder how stable is the "State API" and the "Scheduled" layer API? For I do not need compile for now, my main concern is those following api:
1. state api: `add_state`, `state_ref`, `state_mut`, `remove_state`
2. Handoff, especially VecHandoff
3. `add_subgraph` and `Port` & `PortCtx`

Does those above APIs have any plan of major change(As in require very large change to project using hydroflow in scheduled style) in near future?

**Comment by MingweiSamuel** [comment]
No plans to change those APIs any time soon, they have been pretty stable
